version: "3.4"

services:
    web:
        image: nginx:1.13-alpine
        ports:
            - 80:80
        networks:
            - stacknet
    backend:
        image: php:7.2-fpm-stretch
        networks:
            - stacknet

networks:
    stacknet:

configs:
    nginx_config:
        file: ./docker/nginx/nginx.conf